/**
 * Built-in component library: passives, switching devices, sources, power and
 * instruments.
 *
 * Each entry documents — in its `ModelCard` — what is simulated, what is
 * approximated, what is idealised and what is not modelled. These cards are
 * displayed verbatim in the UI and exported with every report.
 *
 * The digital primitives live in `primitives-digital.ts`, the semiconductor
 * devices in `primitives-semi.ts`.
 */

import { Accuracy } from './labels.js';
import type { ModelCard } from './labels.js';
import type { ComponentSpec, SymbolShape } from './library.js';
import { Kind } from './kinds.js';

// ---------------------------------------------------------------------------
// Symbol helpers
// ---------------------------------------------------------------------------

/** Standard 2-pin vertical symbol: pins at (0,-2) and (0,2). */
export const PIN_TOP = { x: 0, y: -2 };
export const PIN_BOTTOM = { x: 0, y: 2 };

/** Resistor body (IEC rectangle) as a reusable shape list. */
function resistorBody(w = 0.75, h = 1.5): SymbolShape[] {
  return [
    { k: 'line', x1: 0, y1: -2, x2: 0, y2: -h },
    { k: 'line', x1: 0, y1: h, x2: 0, y2: 2 },
    { k: 'rect', x: -w, y: -h, w: 2 * w, h: 2 * h, t: 0.14 },
  ];
}

const REF = (prefix: string): string => prefix;

// ---------------------------------------------------------------------------
// PASSIVES
// ---------------------------------------------------------------------------

const resistorCard: ModelCard = {
  family: 'Linear resistor with first-order parasitics',
  version: '1.0.0',
  claims: [
    {
      phenomenon: 'static I-V',
      level: Accuracy.REALISTIC,
      detail: 'Ohm law V = R·I, exact for the linear model; the DC solver returns this to machine precision.',
      validity: 'any V/I within the declared maximum ratings',
    },
    {
      phenomenon: 'temperature dependence',
      level: Accuracy.APPROXIMATED,
      detail: 'R(T) = R·(1 + tc1·ΔT + tc2·ΔT²) with ΔT = T − Tnom. This is the standard datasheet fit; real resistors have higher-order curvature.',
      validity: '|ΔT| < 100 °C',
    },
    {
      phenomenon: 'self-heating',
      level: Accuracy.REALISTIC,
      detail:
        'At level 3 the dissipated power P = v·i is injected into the device thermal node (Rth, Cth) and raises T, which feeds back into R(T).',
      validity: 'valid while the device stays within its linear thermal model',
    },
    {
      phenomenon: 'parasitic inductance / capacitance',
      level: Accuracy.APPROXIMATED,
      detail:
        'Optional lumped series inductance ESL and parallel capacitance EPC turn the element into a series R-L branch in parallel with C. Accurate up to the first resonance.',
      validity: 'f < 1/(2π·√(L·C)) / 3',
    },
    {
      phenomenon: 'thermal noise',
      level: Accuracy.REALISTIC,
      detail: 'Johnson–Nyquist voltage noise density √(4kTR) is generated by the noise analysis (`.noise` style), sampled from the seeded RNG.',
    },
    {
      phenomenon: 'aging / drift / magnetostriction',
      level: Accuracy.NOT_MODELED,
      detail: 'Long-term drift and mechanical effects are not represented.',
    },
    {
      phenomenon: 'tolerance',
      level: Accuracy.APPROXIMATED,
      detail: 'The `tol` parameter is used only by Monte-Carlo analysis, never during a nominal simulation.',
    },
  ],
  equations: ['V = R(t)·I', 'R(T) = R·(1 + tc1·ΔT + tc2·ΔT²)', 'P = V·I', 'Cth·dT/dt = P − (T − Tamb)/Rth', 'S_v = 4kT·R  [V²/Hz]'],
  parameters: [
    { name: 'r', unit: 'Ω', meaning: 'nominal resistance at Tnom' },
    { name: 'tc1', unit: '1/°C', meaning: 'linear temperature coefficient' },
    { name: 'tc2', unit: '1/°C²', meaning: 'quadratic temperature coefficient' },
    { name: 'rth', unit: '°C/W', meaning: 'junction-to-ambient thermal resistance' },
    { name: 'cth', unit: 'J/°C', meaning: 'thermal capacitance' },
  ],
  limitations: [
    'No voltage-dependent nonlinearity (use a varistor for that).',
    'Parasitics are lumped, not distributed: useless above ~1 GHz for normal packages.',
    'Tolerance and drift are statistical, not simulated in nominal runs.',
  ],
  references: ['IEC 60115 (resistor datasheets)', 'Johnson 1928 / Nyquist 1928 (thermal noise)'],
  levels: [1, 2, 3],
};

const capacitorCard: ModelCard = {
  family: 'Linear capacitor with ESR/ESL and leakage',
  version: '1.0.0',
  claims: [
    {
      phenomenon: 'static charge storage',
      level: Accuracy.REALISTIC,
      detail: 'i = C·dv/dt integrated with the trapezoidal or backward-Euler companion model.',
    },
    {
      phenomenon: 'equivalent series resistance / inductance',
      level: Accuracy.APPROXIMATED,
      detail: 'ESR in series with the capacitance, ESL in series with that: the element becomes a series RLC branch, which is the accepted first-order model.',
      validity: 'valid up to the self-resonant frequency and somewhat beyond',
    },
    {
      phenomenon: 'dielectric absorption',
      level: Accuracy.APPROXIMATED,
      detail:
        'When enabled, modelled as a second RC branch (two-branch model) — reproduces the standard DA signature (voltage rebound after discharge) but not the full stretched-exponential curve.',
    },
    {
      phenomenon: 'voltage coefficient',
      level: Accuracy.APPROXIMATED,
      detail: 'C(V) = C·(1 + vc1·V) linear fit, meaningful for class-2 ceramics and supercapacitors.',
    },
    {
      phenomenon: 'leakage',
      level: Accuracy.REALISTIC,
      detail: 'Bulk leakage modelled as a parallel resistance computed from the leak parameter (insulation resistance · µF).',
    },
    {
      phenomenon: 'dielectric breakdown',
      level: Accuracy.APPROXIMATED,
      detail:
        'Above vmax the model switches to a low-value resistance (0.1 Ω) and raises a SHORT_CIRCUIT/OVERSTRESS diagnostic. This is a failure flag, not a breakdown physics simulation.',
    },
    {
      phenomenon: 'electrolytic wear-out / ESR ageing',
      level: Accuracy.NOT_MODELED,
      detail: 'End-of-life drift of electrolytic capacitors is not simulated.',
    },
  ],
  equations: ['i = C·dv/dt', 'Z(ω) = ESR + jωESL + 1/(jωC)', 'R_leak = insulation·1e6 / C[µF]', 'DA: C_da·dv_da/dt = (v − v_da)/R_da − v_da/R_bleed'],
  parameters: [
    { name: 'c', unit: 'F', meaning: 'capacitance' },
    { name: 'esr', unit: 'Ω', meaning: 'equivalent series resistance' },
    { name: 'esl', unit: 'H', meaning: 'equivalent series inductance' },
    { name: 'leak', unit: 'MΩ·µF', meaning: 'insulation quality (leakage)' },
  ],
  limitations: [
    'No temperature-dependent capacitance (a `tc1` term exists but class-3 ceramics are strongly nonlinear).',
    'Breakdown is a flagged resistance change, not a physics model of oxide rupture.',
  ],
  references: ['IEC 60384', 'Kemet/TDK application notes on ceramic DC bias'],
  levels: [1, 2, 3],
};

const inductorCard: ModelCard = {
  family: 'Inductor with DCR, saturation and core loss',
  version: '1.0.0',
  claims: [
    {
      phenomenon: 'static flux linkage',
      level: Accuracy.REALISTIC,
      detail: 'v = L·di/dt with winding resistance in series; exact for the linear inductance.',
    },
    {
      phenomenon: 'magnetic saturation',
      level: Accuracy.APPROXIMATED,
      detail:
        'L(i) = L0 / (1 + (i/Isat)²). Reproduces the monotonic collapse of inductance with current and the resulting current-spike distortion; the exact B–H curve of a given core is not reproduced.',
      validity: 'up to ~3·Isat',
    },
    {
      phenomenon: 'core loss',
      level: Accuracy.APPROXIMATED,
      detail: 'Steinmetz-style loss R_core(ω) applied as a parallel resistance computed from the core-loss coefficient and frequency.',
    },
    {
      phenomenon: 'self-resonance',
      level: Accuracy.REALISTIC,
      detail: 'Parallel EPC makes the element resonate at 1/(2π√(L·C)); the resonant behaviour above that point is reproduced by the lumped model.',
    },
    {
      phenomenon: 'hysteresis / eddy current distribution',
      level: Accuracy.NOT_MODELED,
      detail: 'No B–H loop with hysteresis: no remanence, no minor-loop behaviour.',
    },
  ],
  equations: ['v = L(i)·di/dt + i·DCR', 'L(i) = L0/(1+(i/Isat)²)', 'R_core = k·ω^α (parallel)', 'f_res = 1/(2π√(L·EPC))'],
  parameters: [
    { name: 'l', unit: 'H', meaning: 'nominal inductance' },
    { name: 'dcr', unit: 'Ω', meaning: 'winding DC resistance' },
    { name: 'isat', unit: 'A', meaning: 'saturation current' },
  ],
  limitations: ['No hysteresis: a swinging inductor will not show remanence or minor loops.'],
  references: ['Erickson & Maksimović, Fundamentals of Power Electronics, ch. 13'],
  levels: [1, 2, 3],
};

const potentiometerCard: ModelCard = {
  family: 'Three-terminal resistive divider with taper',
  version: '1.0.0',
  claims: [
    { phenomenon: 'division ratio', level: Accuracy.REALISTIC, detail: 'Two resistors R_top = R·(1−w) and R_bot = R·w solved exactly by the MNA solver.' },
    {
      phenomenon: 'taper (log/linear)',
      level: Accuracy.APPROXIMATED,
      detail: 'The wiper ratio is remapped through the selected taper law; real pot tapers are piecewise and manufacturing-dependent.',
    },
    { phenomenon: 'wiper resistance and end resistance', level: Accuracy.REALISTIC, detail: 'Both are modelled as explicit series resistances in the branch.' },
    { phenomenon: 'mechanical noise / wear', level: Accuracy.NOT_MODELED, detail: 'No contact intermittency or wear model.' },
  ],
  equations: ['Rt = R·(1−w) + Rw', 'Rb = R·w + Rw', 'log taper: w = 10^(−2·(1−p))'],
  parameters: [
    { name: 'r', unit: 'Ω', meaning: 'total end-to-end resistance' },
    { name: 'wiper', unit: '', meaning: 'wiper position 0..1' },
    { name: 'taper', unit: '', meaning: 'linear or log' },
  ],
  limitations: ['A single wiper: multi-turn mechanical models are not simulated.'],
  references: ['Bourns trimmer datasheets'],
  levels: [1, 2, 3],
};

const transformerCard: ModelCard = {
  family: 'Coupled inductors (ideal-transformer limit with leakage)',
  version: '1.0.0',
  claims: [
    { phenomenon: 'voltage/current transfer', level: Accuracy.REALISTIC, detail: 'Mutual inductance M = k·√(L1·L2) stamped into the MNA matrix; Faraday law solved directly.' },
    { phenomenon: 'leakage inductance', level: Accuracy.REALISTIC, detail: 'Emitted naturally by k < 1 (leakage = L·(1−k) referred to each side).' },
    { phenomenon: 'core saturation', level: Accuracy.APPROXIMATED, detail: 'Both windings share a saturating inductance law driven by magnetising current; deep saturation with hysteresis is not reproduced.' },
    { phenomenon: 'core loss / eddy currents', level: Accuracy.APPROXIMATED, detail: 'A single core-loss resistance across the magnetising inductance.' },
    { phenomenon: 'winding capacitance / inter-winding capacitance', level: Accuracy.NOT_MODELED, detail: 'Not modelled; irrelevant below ~1 MHz for mains transformers.' },
  ],
  equations: ['v1 = L1·di1/dt + M·di2/dt', 'v2 = M·di1/dt + L2·di2/dt', 'M = k·√(L1·L2)', 'n = √(L2/L1)'],
  parameters: [
    { name: 'l1', unit: 'H', meaning: 'primary inductance' },
    { name: 'l2', unit: 'H', meaning: 'secondary inductance' },
    { name: 'k', unit: '', meaning: 'coupling coefficient 0..1' },
  ],
  limitations: ['No hysteresis, no skin effect, no inter-winding capacitance.'],
  references: ['Erickson & Maksimović ch. 13'],
  levels: [1, 2, 3],
};

const thermistorCard: ModelCard = {
  family: 'NTC thermistor, exponential B-coefficient model',
  version: '1.0.0',
  claims: [
    {
      phenomenon: 'resistance vs temperature',
      level: Accuracy.REALISTIC,
      detail: 'R(T) = R25·exp(B·(1/T − 1/298.15)) with T in kelvin — the industry-standard B model (accurate to a few % over 0–100 °C).',
      validity: '−40 °C … +150 °C',
    },
    {
      phenomenon: 'self-heating',
      level: Accuracy.REALISTIC,
      detail: 'Dissipated power heats the body through Rth/Cth, which shifts R — this is the mechanism used by self-heated airflow sensors, and it emerges naturally here.',
    },
    { phenomenon: 'Steinhart–Hart fit', level: Accuracy.NOT_MODELED, detail: 'The three-coefficient Steinhart–Hart equation is not used; the B model is less accurate near the range edges.' },
  ],
  equations: ['R(T) = R25·exp(B·(1/T − 1/T25))'],
  parameters: [
    { name: 'r25', unit: 'Ω', meaning: 'resistance at 25 °C' },
    { name: 'b', unit: 'K', meaning: 'B coefficient (typically 3000–5000 K)' },
  ],
  limitations: ['Accuracy degrades outside −40…+150 °C.', 'No ageing drift.'],
  references: ['NTC thermistor B-constant model, IEC 60539'],
  levels: [1, 2, 3],
};

const varistorCard: ModelCard = {
  family: 'Metal-oxide varistor, power-law clamp',
  version: '1.0.0',
  claims: [
    {
      phenomenon: 'clamping behaviour',
      level: Accuracy.APPROXIMATED,
      detail: 'I = sign(V)·k·|V/Vref|^α with α typically 20–60. Captures the sharp knee and the clamp voltage; the actual grain-boundary physics is not modelled.',
      validity: '|V| < 2·Vref',
    },
    { phenomenon: 'energy absorption / degradation', level: Accuracy.NOT_MODELED, detail: 'Cumulative energy degradation is tracked only as a diagnostic, not as a model of the device failing.' },
  ],
  equations: ['i = sign(v)·k·|v/vref|^α'],
  parameters: [
    { name: 'vref', unit: 'V', meaning: 'reference (clamp) voltage at 1 mA' },
    { name: 'alpha', unit: '', meaning: 'nonlinearity exponent' },
  ],
  limitations: ['No temperature dependence of the clamp voltage.', 'No wear-out.'],
  references: ['Littelfuse varistor datasheets'],
  levels: [1, 2],
};

export const PASSIVE_SPECS: ComponentSpec[] = [
  {
    id: 'resistor',
    name: 'Resistor',
    category: 'passive',
    description: 'Linear resistor with optional temperature coefficient, self-heating and parasitics.',
    refPrefix: 'R',
    spicePrefix: 'R',
    footprint: 'THT/R_0805',
    examplePart: 'RC0805FR-0710KL',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: PIN_TOP.x, y: PIN_TOP.y },
      { name: '2', direction: 'passive', electrical: 'analog', x: PIN_BOTTOM.x, y: PIN_BOTTOM.y },
    ],
    params: [
      { name: 'r', kind: 'number', unit: 'ohm', default: 10000, min: 1e-6, max: 1e15, description: 'Resistance at the nominal temperature', sensitive: true },
      { name: 'tc1', kind: 'number', unit: '', default: 100e-6, description: 'Linear temperature coefficient (1/°C)', deviceParameter: true },
      { name: 'tc2', kind: 'number', unit: '', default: 0, description: 'Quadratic temperature coefficient (1/°C²)', deviceParameter: true },
      { name: 'tol', kind: 'number', unit: '', default: 1, min: 0, max: 50, description: 'Tolerance in % (used by Monte-Carlo analysis only)', deviceParameter: true },
      { name: 'pmax', kind: 'number', unit: 'watt', default: 0.125, min: 0, description: 'Rated power dissipation (overstress flag)', deviceParameter: true },
      { name: 'vmax', kind: 'number', unit: 'volt', default: 150, min: 0, description: 'Maximum working voltage', deviceParameter: true },
      { name: 'esl', kind: 'number', unit: 'henry', default: 0, min: 0, description: 'Series parasitic inductance (0 = ideal)' },
      { name: 'epc', kind: 'number', unit: 'farad', default: 0, min: 0, description: 'Parallel parasitic capacitance (0 = ideal)' },
      { name: 'rth', kind: 'number', unit: '', default: 200, min: 0.01, description: 'Thermal resistance junction-ambient (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 0.005, min: 1e-12, description: 'Thermal capacitance (J/°C)' },
      { name: 'noise', kind: 'boolean', default: true, description: 'Include Johnson–Nyquist thermal noise in noise analysis' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: resistorCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['R'] },
    symbol: resistorBody(),
    keywords: ['r', 'res', 'ohm'],
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    category: 'passive',
    description: 'Capacitor with ESR, ESL, leakage, dielectric absorption and breakdown flag.',
    refPrefix: 'C',
    spicePrefix: 'C',
    footprint: 'SMD/C_0805',
    examplePart: 'GRM21BR71H104KA01L',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '2', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'c', kind: 'number', unit: 'farad', default: 100e-9, min: 1e-15, max: 1e6, description: 'Capacitance', sensitive: true },
      { name: 'polarized', kind: 'boolean', default: false, description: 'Electrolytic-style polarity (reverse voltage flag)' },
      { name: 'esr', kind: 'number', unit: 'ohm', default: 0.05, min: 0, description: 'Equivalent series resistance' },
      { name: 'esl', kind: 'number', unit: 'henry', default: 0, min: 0, description: 'Equivalent series inductance' },
      { name: 'leak', kind: 'number', unit: '', default: 1000, min: 0, description: 'Insulation resistance in MΩ·µF (0 = no leakage)' },
      { name: 'vmax', kind: 'number', unit: 'volt', default: 50, min: 0, description: 'Maximum voltage (breakdown threshold)', deviceParameter: true },
      { name: 'vc1', kind: 'number', unit: '', default: 0, description: 'Voltage coefficient (1/V), class-2 ceramics' },
      { name: 'da', kind: 'boolean', default: false, description: 'Model dielectric absorption as a second RC branch' },
      { name: 'rth', kind: 'number', unit: '', default: 100, min: 0.01, description: 'Thermal resistance (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 0.01, min: 1e-12, description: 'Thermal capacitance (J/°C)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: capacitorCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['C'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -0.25 },
      { k: 'line', x1: 0, y1: 0.25, x2: 0, y2: 2 },
      { k: 'line', x1: -0.85, y1: -0.25, x2: 0.85, y2: -0.25, t: 0.2 },
      { k: 'line', x1: -0.85, y1: 0.25, x2: 0.85, y2: 0.25, t: 0.2 },
    ],
    keywords: ['c', 'cap', 'capacitor'],
  },
  {
    id: 'inductor',
    name: 'Inductor',
    category: 'passive',
    description: 'Inductor with DCR, saturation, core loss and self-resonance.',
    refPrefix: 'L',
    spicePrefix: 'L',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '2', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'l', kind: 'number', unit: 'henry', default: 1e-3, min: 1e-12, description: 'Nominal inductance', sensitive: true },
      { name: 'dcr', kind: 'number', unit: 'ohm', default: 0.1, min: 0, description: 'Winding DC resistance' },
      { name: 'isat', kind: 'number', unit: 'amp', default: 1, min: 1e-9, description: 'Saturation current (L halves at ~1.7·Isat)' },
      { name: 'epc', kind: 'number', unit: 'farad', default: 2e-12, min: 0, description: 'Parallel parasitic capacitance' },
      { name: 'coreLoss', kind: 'number', unit: '', default: 0, min: 0, description: 'Steinmetz core loss coefficient (0 = none)' },
      { name: 'ilm', kind: 'number', unit: 'amp', default: 10, min: 0, description: 'Maximum rated current (overstress flag)' },
      { name: 'rth', kind: 'number', unit: '', default: 40, min: 0.01, description: 'Thermal resistance (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 0.02, min: 1e-12, description: 'Thermal capacitance (J/°C)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: inductorCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['L'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1.1 },
      { k: 'line', x1: 0, y1: 1.1, x2: 0, y2: 2 },
      { k: 'arc', cx: -0.55, cy: -0.825, r: 0.275, a0: 90, a1: 270, t: 0.13 },
      { k: 'arc', cx: -0.55, cy: -0.275, r: 0.275, a0: 90, a1: 270, t: 0.13 },
      { k: 'arc', cx: -0.55, cy: 0.275, r: 0.275, a0: 90, a1: 270, t: 0.13 },
      { k: 'arc', cx: -0.55, cy: 0.825, r: 0.275, a0: 90, a1: 270, t: 0.13 },
      { k: 'line', x1: 0, y1: -1.1, x2: -0.55, y2: -1.1, t: 0.13 },
      { k: 'line', x1: -0.55, y1: -0.55, x2: -0.55, y2: 0.55, t: 0.13 },
      { k: 'line', x1: -0.55, y1: 1.1, x2: 0, y2: 1.1, t: 0.13 },
    ],
    keywords: ['l', 'ind', 'coil', 'choke'],
  },
  {
    id: 'potentiometer',
    name: 'Potentiometer',
    category: 'passive',
    description: 'Three-terminal variable resistor with taper, wiper resistance and end resistance.',
    refPrefix: 'RV',
    spicePrefix: 'R',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: 'W', direction: 'passive', electrical: 'analog', x: 2, y: 0, description: 'Wiper' },
      { name: '3', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'r', kind: 'number', unit: 'ohm', default: 10000, min: 1, description: 'End-to-end resistance', sensitive: true },
      { name: 'wiper', kind: 'number', unit: '', default: 0.5, min: 0, max: 1, step: 0.01, description: 'Wiper position (0 = pin 1, 1 = pin 3)', sensitive: true },
      { name: 'taper', kind: 'choice', default: 'linear', choices: ['linear', 'log'], description: 'Taper law' },
      { name: 'rw', kind: 'number', unit: 'ohm', default: 1, min: 0, description: 'Wiper contact resistance' },
      { name: 'rterm', kind: 'number', unit: 'ohm', default: 2, min: 0, description: 'End resistance (minimum resistance at either extreme)' },
      { name: 'pmax', kind: 'number', unit: 'watt', default: 0.25, min: 0, description: 'Rated power' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: potentiometerCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['R', 'R'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1.5 },
      { k: 'line', x1: 0, y1: 1.5, x2: 0, y2: 2 },
      { k: 'rect', x: -0.75, y: -1.5, w: 1.5, h: 3, t: 0.14 },
      { k: 'line', x1: 2, y1: 0, x2: 0.75, y2: 0, t: 0.14 },
      { k: 'filled', pts: [0.75, 0, 0.2, 0.35, 0.2, -0.35] },
    ],
    keywords: ['pot', 'trimmer', 'vr'],
  },
  {
    id: 'transformer',
    name: 'Transformer',
    category: 'passive',
    description: 'Two coupled windings with coupling coefficient, winding resistance and core loss.',
    refPrefix: 'T',
    spicePrefix: 'L',
    pins: [
      { name: 'P1', direction: 'passive', electrical: 'analog', x: -2, y: -1 },
      { name: 'P2', direction: 'passive', electrical: 'analog', x: -2, y: 1 },
      { name: 'S1', direction: 'passive', electrical: 'analog', x: 2, y: -1 },
      { name: 'S2', direction: 'passive', electrical: 'analog', x: 2, y: 1 },
    ],
    params: [
      { name: 'l1', kind: 'number', unit: 'henry', default: 1, min: 1e-9, description: 'Primary inductance', sensitive: true },
      { name: 'l2', kind: 'number', unit: 'henry', default: 0.01, min: 1e-9, description: 'Secondary inductance (turns ratio = √(L2/L1))', sensitive: true },
      { name: 'k', kind: 'number', unit: '', default: 0.995, min: 0.0001, max: 0.999999, description: 'Coupling coefficient', sensitive: true },
      { name: 'rp', kind: 'number', unit: 'ohm', default: 1, min: 0, description: 'Primary winding resistance' },
      { name: 'rs', kind: 'number', unit: 'ohm', default: 0.1, min: 0, description: 'Secondary winding resistance' },
      { name: 'coreLoss', kind: 'number', unit: '', default: 0, min: 0, description: 'Core loss coefficient (0 = none)' },
      { name: 'rth', kind: 'number', unit: '', default: 20, min: 0.01, description: 'Thermal resistance (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 0.5, min: 1e-9, description: 'Thermal capacitance (J/°C)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: transformerCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['L', 'L'] },
    symbol: [
      { k: 'line', x1: -2, y1: -1, x2: -1.2, y2: -1 },
      { k: 'line', x1: -2, y1: 1, x2: -1.2, y2: 1 },
      { k: 'line', x1: -1.2, y1: -1, x2: -1.2, y2: -0.6 },
      { k: 'line', x1: -1.2, y1: 0.6, x2: -1.2, y2: 1 },
      { k: 'arc', cx: -0.8, cy: -0.9, r: 0.3, a0: 0, a1: 180, t: 0.12 },
      { k: 'arc', cx: -0.8, cy: -0.3, r: 0.3, a0: 0, a1: 180, t: 0.12 },
      { k: 'arc', cx: -0.8, cy: 0.3, r: 0.3, a0: 0, a1: 180, t: 0.12 },
      { k: 'arc', cx: -0.8, cy: 0.9, r: 0.3, a0: 0, a1: 180, t: 0.12 },
      { k: 'line', x1: -0.4, y1: -1, x2: -0.4, y2: 1, t: 0.1 },
      { k: 'line', x1: -0.15, y1: -1, x2: -0.15, y2: 1, t: 0.1 },
      { k: 'arc', cx: 0.2, cy: -0.9, r: 0.3, a0: 180, a1: 360, t: 0.12 },
      { k: 'arc', cx: 0.2, cy: -0.3, r: 0.3, a0: 180, a1: 360, t: 0.12 },
      { k: 'arc', cx: 0.2, cy: 0.3, r: 0.3, a0: 180, a1: 360, t: 0.12 },
      { k: 'arc', cx: 0.2, cy: 0.9, r: 0.3, a0: 180, a1: 360, t: 0.12 },
      { k: 'line', x1: 0.6, y1: -1, x2: 1.2, y2: -1 },
      { k: 'line', x1: 0.6, y1: 1, x2: 1.2, y2: 1 },
      { k: 'line', x1: 1.2, y1: -1, x2: 1.2, y2: 2 },
      { k: 'line', x1: 1.2, y1: 1, x2: 2, y2: 1 },
    ],
    keywords: ['xfmr', 'transformer'],
  },
  {
    id: 'ntc_thermistor',
    name: 'NTC Thermistor',
    category: 'passive',
    description: 'Temperature-dependent resistor (B-coefficient model) with self-heating.',
    refPrefix: 'RT',
    spicePrefix: 'R',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '2', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'r25', kind: 'number', unit: 'ohm', default: 10000, min: 1e-3, description: 'Resistance at 25 °C', sensitive: true },
      { name: 'b', kind: 'number', unit: '', default: 3950, min: 100, max: 20000, description: 'B coefficient in kelvin', sensitive: true },
      { name: 'rth', kind: 'number', unit: '', default: 80, min: 0.01, description: 'Thermal resistance (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 0.002, min: 1e-9, description: 'Thermal capacitance (J/°C)' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: thermistorCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['R'] },
    symbol: [
      ...resistorBody(),
      { k: 'line', x1: -1.1, y1: 1.5, x2: -0.35, y2: 0.75, t: 0.12 },
      { k: 'text', x: -1.2, y: 1.9, s: 'ϑ', size: 0.7 },
    ],
    keywords: ['ntc', 'thermistor', 'temp'],
  },
  {
    id: 'varistor',
    name: 'Varistor (MOV)',
    category: 'passive',
    description: 'Metal-oxide varistor with power-law clamping characteristic.',
    refPrefix: 'RV',
    spicePrefix: 'R',
    pins: [
      { name: '1', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '2', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'vref', kind: 'number', unit: 'volt', default: 24, min: 0.1, description: 'Clamp voltage at 1 mA', sensitive: true },
      { name: 'alpha', kind: 'number', unit: '', default: 30, min: 2, max: 200, description: 'Nonlinearity exponent', sensitive: true },
      { name: 'leak', kind: 'number', unit: 'siemens', default: 1e-9, min: 0, description: 'Off-state leakage conductance' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: varistorCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['R'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1.2 },
      { k: 'line', x1: 0, y1: 1.2, x2: 0, y2: 2 },
      { k: 'rect', x: -0.75, y: -1.2, w: 1.5, h: 2.4, t: 0.14 },
      { k: 'line', x1: -0.45, y1: -1.2, x2: 0.45, y2: -0.5, t: 0.1 },
      { k: 'line', x1: -0.45, y1: -0.5, x2: 0.45, y2: 0.2, t: 0.1 },
      { k: 'line', x1: -0.45, y1: 0.2, x2: 0.45, y2: 0.9, t: 0.1 },
    ],
    keywords: ['mov', 'varistor'],
  },
];

// ---------------------------------------------------------------------------
// SWITCHING
// ---------------------------------------------------------------------------

const switchCard: ModelCard = {
  family: 'Two-state resistive switch with contact bounce',
  version: '1.0.0',
  claims: [
    { phenomenon: 'conduction state', level: Accuracy.REALISTIC, detail: 'Modelled as a resistor: Ron when closed, Roff when open — the standard approach for circuit-level switch simulation.' },
    {
      phenomenon: 'contact bounce',
      level: Accuracy.APPROXIMATED,
      detail:
        'Optional bouncing defined by an initial bounce duration, a bounce period and a decay; the pattern is deterministic (seeded), not measured from a specific part.',
    },
    { phenomenon: 'arc / contact erosion / welding', level: Accuracy.NOT_MODELED, detail: 'No arcing, no minimum current, no lifetime model.' },
  ],
  equations: ['R = Ron (closed) / Roff (open)', 'bounce: t_n = Σ bouncePeriod·decay^k'],
  parameters: [
    { name: 'ron', unit: 'Ω', meaning: 'closed resistance' },
    { name: 'roff', unit: 'Ω', meaning: 'open resistance' },
    { name: 'bounces', unit: '', meaning: 'number of bounces' },
  ],
  limitations: ['Contacts are ideal resistors: no arc, no welding, no current-dependent resistance.'],
  references: ['Relay contact bounce measurements, Omron/TE application notes'],
  levels: [0, 1, 2],
};

const relayCard: ModelCard = {
  family: 'Electromagnetic relay: coil + mechanical armature + contacts',
  version: '1.0.0',
  claims: [
    { phenomenon: 'coil electrical behaviour', level: Accuracy.REALISTIC, detail: 'Inductive branch (L, R) solved by the MNA solver; the freewheel-diode effect, the kickback and the current ramp are all reproduced.' },
    {
      phenomenon: 'mechanical actuation',
      level: Accuracy.APPROXIMATED,
      detail:
        'First-order dynamics: armature position x with ẋ = ((F − Fspring)/c) where F ∝ i². Gives the correct pickup/dropout hysteresis and pull-in delay shape, but not the true force/displacement curve of a specific relay.',
      validity: 'coil current > 0 well below the contact rating',
    },
    { phenomenon: 'contact bounce on switching', level: Accuracy.APPROXIMATED, detail: 'Deterministic bounce pattern parameterised per relay.' },
    { phenomenon: 'contact life / arcing', level: Accuracy.NOT_MODELED, detail: 'Not modelled.' },
  ],
  equations: ['v_coil = L·di/dt + R·i', 'F = k·i²', 'x(t) from first-order dynamics', 'NO contact closes when x > x_pickup'],
  parameters: [
    { name: 'lcoil', unit: 'H', meaning: 'coil inductance' },
    { name: 'rcoil', unit: 'Ω', meaning: 'coil resistance' },
    { name: 'vpull', unit: 'V', meaning: 'pull-in voltage' },
  ],
  limitations: ['Armature dynamics are first order, not a mass-spring model with resonance.'],
  references: ['Panasonic TQ relay datasheet'],
  levels: [1, 2],
};

export const SWITCHING_SPECS: ComponentSpec[] = [
  {
    id: 'switch',
    name: 'Switch (SPST)',
    category: 'switching',
    description: 'Manual or state-controlled single-pole switch with optional contact bounce.',
    refPrefix: 'SW',
    spicePrefix: 'S',
    pins: [
      { name: 'A', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: 'B', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'closed', kind: 'boolean', default: false, description: 'Closed at t = 0 (state is also driven by the UI or by a control net)', sensitive: true },
      { name: 'ron', kind: 'number', unit: 'ohm', default: 0.05, min: 1e-6, description: 'Closed resistance' },
      { name: 'roff', kind: 'number', unit: 'ohm', default: 1e9, min: 1, description: 'Open resistance' },
      { name: 'bounce', kind: 'boolean', default: false, description: 'Simulate contact bounce' },
      { name: 'bounces', kind: 'number', unit: '', default: 3, min: 0, max: 30, description: 'Number of bounces' },
      { name: 'bouncePeriod', kind: 'number', unit: 'second', default: 1e-4, min: 1e-9, description: 'Initial bounce period' },
      { name: 'bounceDecay', kind: 'number', unit: '', default: 0.5, min: 0.05, max: 0.95, description: 'Bounce decay factor per period' },
      { name: 'switchAt', kind: 'number', unit: 'second', default: 0, description: 'Time of the state change (for scripted runs)', sensitive: true },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: switchCard,
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['SW'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1 },
      { k: 'line', x1: 0, y1: 1, x2: 0, y2: 2 },
      { k: 'circle', cx: 0, cy: -1, r: 0.12 },
      { k: 'circle', cx: 0, cy: 1, r: 0.12 },
      { k: 'line', x1: 0, y1: -0.88, x2: 0.9, y2: 0.85, t: 0.14 },
    ],
    keywords: ['sw', 'contact'],
  },
  {
    id: 'push_button',
    name: 'Push Button',
    category: 'switching',
    description: 'Momentary push button (NO or NC) with optional bounce and hold time.',
    refPrefix: 'SB',
    spicePrefix: 'S',
    pins: [
      { name: 'A', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: 'B', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'pressed', kind: 'boolean', default: false, description: 'Pressed at t = 0', sensitive: true },
      { name: 'contact', kind: 'choice', default: 'NO', choices: ['NO', 'NC'], description: 'Normally open or normally closed' },
      { name: 'pressAt', kind: 'number', unit: 'second', default: 0, description: 'Time the button is pressed' },
      { name: 'holdTime', kind: 'number', unit: 'second', default: 0, description: 'How long it stays pressed (0 = never released)' },
      { name: 'ron', kind: 'number', unit: 'ohm', default: 0.1, min: 1e-6, description: 'Contact resistance when conducting' },
      { name: 'roff', kind: 'number', unit: 'ohm', default: 1e7, min: 1, description: 'Open resistance' },
      { name: 'bounce', kind: 'boolean', default: true, description: 'Simulate contact bounce (realistic for mechanical buttons)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: switchCard,
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['SW'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1 },
      { k: 'line', x1: 0, y1: 1, x2: 0, y2: 2 },
      { k: 'circle', cx: 0, cy: -1, r: 0.12 },
      { k: 'circle', cx: 0, cy: 1, r: 0.12 },
      { k: 'line', x1: 0, y1: -0.88, x2: 0.9, y2: 0.85, t: 0.14 },
      { k: 'line', x1: -0.7, y1: -1.7, x2: 0.7, y2: -1.7, t: 0.14 },
      { k: 'line', x1: 0, y1: -1.7, x2: 0, y2: -1.15, t: 0.14 },
    ],
    keywords: ['button', 'sw', 'pb'],
  },
  {
    id: 'relay',
    name: 'Relay',
    category: 'switching',
    description: 'Electromagnetic relay: inductive coil drives a mechanically modelled armature and contacts.',
    refPrefix: 'K',
    spicePrefix: 'X',
    pins: [
      { name: 'A1', direction: 'passive', electrical: 'analog', x: -2, y: -1.5, description: 'Coil +' },
      { name: 'A2', direction: 'passive', electrical: 'analog', x: -2, y: 1.5, description: 'Coil −' },
      { name: 'COM', direction: 'passive', electrical: 'analog', x: 2, y: 0, description: 'Common contact' },
      { name: 'NO', direction: 'passive', electrical: 'analog', x: 2, y: -1.5, description: 'Normally open contact' },
      { name: 'NC', direction: 'passive', electrical: 'analog', x: 2, y: 1.5, description: 'Normally closed contact' },
    ],
    params: [
      { name: 'lcoil', kind: 'number', unit: 'henry', default: 0.05, min: 1e-9, description: 'Coil inductance', sensitive: true },
      { name: 'rcoil', kind: 'number', unit: 'ohm', default: 400, min: 0.01, description: 'Coil resistance', sensitive: true },
      { name: 'vpull', kind: 'number', unit: 'volt', default: 3.5, min: 0.01, description: 'Pull-in (pickup) voltage', sensitive: true },
      { name: 'vdrop', kind: 'number', unit: 'volt', default: 1.5, min: 0, description: 'Drop-out voltage' },
      { name: 'tpull', kind: 'number', unit: 'second', default: 5e-3, min: 1e-9, description: 'Armature travel time (pull-in)' },
      { name: 'tdrop', kind: 'number', unit: 'second', default: 3e-3, min: 1e-9, description: 'Armature travel time (drop-out)' },
      { name: 'ron', kind: 'number', unit: 'ohm', default: 0.05, min: 1e-6, description: 'Contact resistance' },
      { name: 'bounce', kind: 'boolean', default: true, description: 'Contact bounce on switching' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: relayCard,
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['L', 'SW', 'SW'] },
    symbol: [
      { k: 'rect', x: -1.6, y: -2, w: 3.2, h: 4, t: 0.16 },
      { k: 'line', x1: -2, y1: -1.5, x2: -1.2, y2: -1.5 },
      { k: 'line', x1: -2, y1: 1.5, x2: -1.2, y2: 1.5 },
      { k: 'rect', x: -1.2, y: -1.9, w: 0.6, h: 3.8, t: 0.12 },
      { k: 'line', x1: -0.2, y1: -1.9, x2: -0.2, y2: 1.9, t: 0.1, dash: true },
      { k: 'line', x1: 0.2, y1: -1.5, x2: 1.5, y2: -1.5, t: 0.12 },
      { k: 'line', x1: 0.2, y1: 1.5, x2: 1.5, y2: 1.5, t: 0.12 },
      { k: 'line', x1: 0.2, y1: 0, x2: 1.35, y2: -1.2, t: 0.14 },
      { k: 'circle', cx: 1.5, cy: 0, r: 0.12 },
      { k: 'line', x1: 1.5, y1: -1.5, x2: 1.5, y2: -0.12, t: 0.12 },
      { k: 'line', x1: 1.5, y1: 0.12, x2: 1.5, y2: 1.5, t: 0.12 },
      { k: 'line', x1: 1.5, y1: 0, x2: 2, y2: 0, t: 0.12 },
      { k: 'line', x1: 1.5, y1: -1.5, x2: 2, y2: -1.5, t: 0.12 },
      { k: 'line', x1: 1.5, y1: 1.5, x2: 2, y2: 1.5, t: 0.12 },
    ],
    keywords: ['relay', 'coil'],
  },
];

// ---------------------------------------------------------------------------
// SOURCES
// ---------------------------------------------------------------------------

function sourceCard(kind: string, notes: string[]): ModelCard {
  return {
    family: `${kind} ideal source`,
    version: '1.0.0',
    claims: [
      { phenomenon: 'output characteristic', level: Accuracy.REALISTIC, detail: `${kind} is imposed exactly by the solver (branch unknown in MNA), including optional series resistance.` },
      { phenomenon: 'output impedance', level: Accuracy.IDEALIZED, detail: 'Zero by default; set `rs` to model the real source impedance. Ideal sources are a limit case, not a physical device.' },
      { phenomenon: 'noise / ripple / drift', level: Accuracy.NOT_MODELED, detail: 'Not modelled unless added explicitly with a noise source or a series impedance.' },
      ...notes.map((n) => ({ phenomenon: n.split(':')[0].trim(), level: Accuracy.APPROXIMATED, detail: n })),
    ],
    equations: ['V(node) = f(t)  |  I(branch) = f(t)'],
    parameters: [
      { name: 'dc', unit: 'V or A', meaning: 'DC value / offset' },
      { name: 'amp', unit: 'V or A', meaning: 'AC amplitude' },
      { name: 'freq', unit: 'Hz', meaning: 'frequency' },
    ],
    limitations: ['Ideal sources can produce non-physical (infinite) results if shorted — the solver reports this as a singularity, it does not silently clamp.'],
    references: ['SPICE2 source models'],
    levels: [1, 2, 3],
  };
}

function sourceSymbol(kind: 'v' | 'i' | 'vsrc' | 'isrc', ac = false): SymbolShape[] {
  const out: SymbolShape[] = [
    { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1 },
    { k: 'line', x1: 0, y1: 1, x2: 0, y2: 2 },
    { k: 'circle', cx: 0, cy: 0, r: 1 },
  ];
  if (kind === 'v') {
    out.push({ k: 'line', x1: -0.5, y1: 0, x2: 0.5, y2: 0, t: 0.14 });
    out.push({ k: 'line', x1: 0, y1: -0.5, x2: 0, y2: 0.5, t: 0.14 });
  } else if (kind === 'i') {
    out.push({ k: 'line', x1: 0, y1: 0.6, x2: 0, y2: -0.6, t: 0.14 });
    out.push({ k: 'filled', pts: [0, -0.7, 0.35, -0.1, -0.35, -0.1] });
  }
  if (ac) out.push({ k: 'arc', cx: 0, cy: 0, r: 0.55, a0: 200, a1: 340, t: 0.1 });
  return out;
}

/** Build the parameter list shared by waveform sources. */
function waveformParams(what: 'volt' | 'amp'): ComponentSpec['params'] {
  const U = what;
  return [
    { name: 'waveform', kind: 'choice', default: 'sine', choices: ['dc', 'sine', 'square', 'triangle', 'sawtooth', 'pulse', 'clock', 'noise', 'arbitrary'], description: 'Waveform shape', sensitive: true },
    { name: 'dc', kind: 'number', unit: U, default: 0, description: 'DC offset / level', sensitive: true },
    { name: 'amp', kind: 'number', unit: U, default: 1, description: 'Amplitude (peak for sine, half-swing for square)', sensitive: true },
    { name: 'freq', kind: 'number', unit: 'hertz', default: 1000, min: 0, description: 'Frequency', sensitive: true },
    { name: 'phase', kind: 'number', unit: '', default: 0, description: 'Phase in degrees' },
    { name: 'duty', kind: 'number', unit: '', default: 0.5, min: 0, max: 1, description: 'Duty cycle (square / pulse / clock)' },
    { name: 'tr', kind: 'number', unit: 'second', default: 1e-9, min: 0, description: 'Rise time (square / pulse / clock)' },
    { name: 'tf', kind: 'number', unit: 'second', default: 1e-9, min: 0, description: 'Fall time (square / pulse / clock)' },
    { name: 'delay', kind: 'number', unit: 'second', default: 0, description: 'Start delay' },
    { name: 'rs', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Source series resistance (0 = ideal)' },
    { name: 'arbitrary', kind: 'string', default: '', description: 'Arbitrary waveform: "t:v" pairs, e.g. "0:0, 1e-3:5, 2e-3:5, 3e-3:0"' },
  ];
}

export const SOURCE_SPECS: ComponentSpec[] = [
  {
    id: 'vdc',
    name: 'DC Voltage Source',
    category: 'source',
    description: 'Ideal constant voltage source with optional series resistance.',
    refPrefix: 'V',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: [
      { name: 'dc', kind: 'number', unit: 'volt', default: 5, description: 'Voltage', sensitive: true },
      { name: 'rs', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Internal series resistance' },
      { name: 'ilimit', kind: 'number', unit: 'amp', default: 0, min: 0, description: 'Current limit (0 = no limit; > 0 adds a soft compliance)' },
    ],
    accuracy: Accuracy.IDEALIZED,
    model: sourceCard('Voltage source', ['Current limit: a limiting branch is inserted, which is a behavioural clamp, not a real regulator loop.']),
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['VDC'] },
    symbol: sourceSymbol('v'),
    keywords: ['v', 'vdd', 'vcc', 'supply', 'battery'],
  },
  {
    id: 'idc',
    name: 'DC Current Source',
    category: 'source',
    description: 'Ideal constant current source.',
    refPrefix: 'I',
    spicePrefix: 'I',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: [
      { name: 'dc', kind: 'number', unit: 'amp', default: 1e-3, description: 'Current (positive = flows from + to − inside the source)', sensitive: true },
      { name: 'rs', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Parallel (shunt) resistance (0 = none)' },
    ],
    accuracy: Accuracy.IDEALIZED,
    model: sourceCard('Current source', []),
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['IDC'] },
    symbol: sourceSymbol('i'),
    keywords: ['i', 'current'],
  },
  {
    id: 'vac',
    name: 'AC Voltage Source',
    category: 'source',
    description: 'Sinusoidal voltage source; also used to drive small-signal AC analysis.',
    refPrefix: 'V',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: [
      { name: 'amp', kind: 'number', unit: 'volt', default: 1, description: 'Peak amplitude (transient) )', sensitive: true },
      { name: 'freq', kind: 'number', unit: 'hertz', default: 1000, min: 0, description: 'Frequency', sensitive: true },
      { name: 'phase', kind: 'number', unit: '', default: 0, description: 'Phase in degrees' },
      { name: 'dc', kind: 'number', unit: 'volt', default: 0, description: 'DC offset' },
      { name: 'ac', kind: 'number', unit: 'volt', default: 1, description: 'AC analysis magnitude (small-signal)' },
      { name: 'acphase', kind: 'number', unit: '', default: 0, description: 'AC analysis phase' },
      { name: 'rs', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Series resistance' },
    ],
    accuracy: Accuracy.IDEALIZED,
    model: sourceCard('Sinusoidal source', []),
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['VSIN'] },
    symbol: sourceSymbol('v', true),
    keywords: ['ac', 'sine', 'sinusoid', 'signal'],
  },
  {
    id: 'iac',
    name: 'AC Current Source',
    category: 'source',
    description: 'Sinusoidal current source.',
    refPrefix: 'I',
    spicePrefix: 'I',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: [
      { name: 'amp', kind: 'number', unit: 'amp', default: 1e-3, description: 'Peak amplitude', sensitive: true },
      { name: 'freq', kind: 'number', unit: 'hertz', default: 1000, min: 0, description: 'Frequency', sensitive: true },
      { name: 'phase', kind: 'number', unit: '', default: 0, description: 'Phase in degrees' },
      { name: 'dc', kind: 'number', unit: 'amp', default: 0, description: 'DC value' },
      { name: 'ac', kind: 'number', unit: 'amp', default: 1e-3, description: 'AC analysis magnitude' },
    ],
    accuracy: Accuracy.IDEALIZED,
    model: sourceCard('Sinusoidal current source', []),
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['ISIN'] },
    symbol: sourceSymbol('i', true),
    keywords: ['iac', 'sine'],
  },
  {
    id: 'vsignal',
    name: 'Signal Generator',
    category: 'source',
    description: 'Multi-waveform voltage source: sine, square, triangle, sawtooth, pulse, clock, noise, arbitrary.',
    refPrefix: 'V',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: waveformParams('volt'),
    accuracy: Accuracy.APPROXIMATED,
    model: sourceCard('Arbitrary signal source', [
      'Waveform construction: piecewise-linear segments with finite rise/fall times — realistic for a lab generator, but not band-limited (no Gibbs filtering of edges at the transition level).',
      'Noise waveform: white or 1/f, generated from the seeded RNG so runs are reproducible.',
    ]),
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['VPWL'] },
    symbol: sourceSymbol('v', true),
    keywords: ['pulse', 'square', 'triangle', 'saw', 'function', 'awg', 'clock', 'noise'],
  },
  {
    id: 'isignal',
    name: 'Current Signal Generator',
    category: 'source',
    description: 'Multi-waveform current source.',
    refPrefix: 'I',
    spicePrefix: 'I',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: waveformParams('amp'),
    accuracy: Accuracy.APPROXIMATED,
    model: sourceCard('Arbitrary current source', ['Same waveform construction as the voltage version.']),
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['IPWL'] },
    symbol: sourceSymbol('i', true),
    keywords: ['ipulse', 'iwave'],
  },
  {
    id: 'clock',
    name: 'Clock Generator',
    category: 'source',
    description: 'Digital clock source with rise/fall times, duty cycle, jitter and optional startup delay.',
    refPrefix: 'CLK',
    spicePrefix: 'V',
    pins: [
      { name: 'OUT', direction: 'output', electrical: 'digital', x: 2, y: 0 },
      { name: '-', direction: 'passive', electrical: 'ground', x: -2, y: 0 },
    ],
    params: [
      { name: 'freq', kind: 'number', unit: 'hertz', default: 1e6, min: 1e-3, description: 'Clock frequency', sensitive: true },
      { name: 'vhigh', kind: 'number', unit: 'volt', default: 3.3, description: 'Logic high level', sensitive: true },
      { name: 'vlow', kind: 'number', unit: 'volt', default: 0, description: 'Logic low level' },
      { name: 'duty', kind: 'number', unit: '', default: 0.5, min: 0.001, max: 0.999, description: 'Duty cycle', sensitive: true },
      { name: 'tr', kind: 'number', unit: 'second', default: 1e-9, min: 0, description: 'Rise time (10–90%)' },
      { name: 'tf', kind: 'number', unit: 'second', default: 1e-9, min: 0, description: 'Fall time (10–90%)' },
      { name: 'rs', kind: 'number', unit: 'ohm', default: 25, min: 0, description: 'Output impedance' },
      { name: 'jitter', kind: 'number', unit: 'second', default: 0, min: 0, description: 'RMS period jitter (seeded random)' },
      { name: 'delay', kind: 'number', unit: 'second', default: 0, description: 'Start delay' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: sourceCard('Clock source', [
      'Jitter: period jitter is drawn from the seeded RNG with the given RMS — it reproduces the timing effect but is not a phase-noise spectrum.',
      'Rise/fall times: linear ramp between the 10% and 90% points (a real driver is closer to a tanh); the resulting delay error is below 10% of the transition time.',
    ]),
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['VCLK'] },
    symbol: [
      { k: 'rect', x: -1.6, y: -1.2, w: 3.2, h: 2.4, t: 0.16, r: 0.25 },
      { k: 'line', x1: 2, y1: 0, x2: 1.6, y2: 0 },
      { k: 'line', x1: -2, y1: 0, x2: -1.6, y2: 0 },
      { k: 'poly', pts: [-1.1, 0.5, -0.6, 0.5, -0.6, -0.5, 0, -0.5, 0, 0.5, 0.6, 0.5, 0.6, -0.5, 1.1, -0.5], t: 0.13 },
    ],
    keywords: ['clk', 'oscillator', 'xtal'],
  },
  {
    id: 'noise_source',
    name: 'Noise Source',
    category: 'source',
    description: 'Voltage or current noise with white / 1/f / band-limited spectral shaping.',
    refPrefix: 'VN',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'mode', kind: 'choice', default: 'voltage', choices: ['voltage', 'current'], description: 'Voltage or current noise' },
      { name: 'density', kind: 'number', unit: '', default: 10e-9, min: 0, description: 'White noise density (V/√Hz or A/√Hz)', sensitive: true },
      { name: 'flicker', kind: 'number', unit: '', default: 0, min: 0, description: '1/f corner density at 1 Hz' },
      { name: 'bwLow', kind: 'number', unit: 'hertz', default: 0, min: 0, description: 'Low cut-off (0 = DC)' },
      { name: 'bwHigh', kind: 'number', unit: 'hertz', default: 1e6, min: 0, description: 'High cut-off' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: {
      ...sourceCard('Noise source', []),
      family: 'Synthetic noise generator',
      claims: [
        { phenomenon: 'white noise density', level: Accuracy.REALISTIC, detail: 'Gaussian samples scaled to the requested spectral density and the simulation bandwidth: σ = density·√(BW).' },
        { phenomenon: '1/f (flicker) noise', level: Accuracy.APPROXIMATED, detail: 'Generated by summing octave-spaced white sources (a standard, if crude, 1/f approximation); the slope is approximately −1 over the band.' },
        { phenomenon: 'spectral shaping beyond 1/f', level: Accuracy.NOT_MODELED, detail: 'No arbitrary spectral masks (use the ARB waveform or a filter).' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['VNOISE'] },
    symbol: [
      ...sourceSymbol('v'),
      { k: 'line', x1: -0.7, y1: -0.85, x2: 0.7, y2: 0.85, t: 0.1 },
      { k: 'line', x1: -0.7, y1: 0.85, x2: 0.7, y2: -0.85, t: 0.1 },
    ],
    keywords: ['noise', 'random', 'thermal'],
  },
  {
    id: 'vcvs',
    name: 'VCVS (E)',
    category: 'source',
    description: 'Voltage-controlled voltage source, gain Av = Vout / (Vp − Vn).',
    refPrefix: 'E',
    spicePrefix: 'E',
    pins: [
      { name: 'OUT+', direction: 'output', electrical: 'analog', x: 3, y: -1.5 },
      { name: 'OUT-', direction: 'output', electrical: 'analog', x: 3, y: 1.5 },
      { name: 'IN+', direction: 'input', electrical: 'analog', x: -3, y: -1.5 },
      { name: 'IN-', direction: 'input', electrical: 'analog', x: -3, y: 1.5 },
    ],
    params: [
      { name: 'gain', kind: 'number', unit: '', default: 10, description: 'Voltage gain', sensitive: true },
      { name: 'rout', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Output resistance' },
      { name: 'rin', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Input resistance (0 = ideal, no loading)' },
      { name: 'vmax', kind: 'number', unit: 'volt', default: 0, min: 0, description: 'Output saturation magnitude (0 = ideal, no clipping)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: {
      ...sourceCard('VCVS', ['Saturation: optional symmetric clipping, which is a behavioural approximation of a real amplifier’s rail limit.']),
      claims: [
        { phenomenon: 'transfer function', level: Accuracy.REALISTIC, detail: 'Imposed exactly as a constraint in the MNA system, so it is exact for the given gain and output resistance.' },
        { phenomenon: 'bandwidth / slew / distortion', level: Accuracy.NOT_MODELED, detail: 'No frequency-dependent gain: build the real amplifier from transistors if you need those effects.' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['E'] },
    symbol: [
      { k: 'poly', pts: [-2.2, -1.8, 2.2, -1.8, 2.2, 1.8, -2.2, 1.8], t: 0.16 },
      { k: 'line', x1: -3, y1: -1.5, x2: -2.2, y2: -1.5 },
      { k: 'line', x1: -3, y1: 1.5, x2: -2.2, y2: 1.5 },
      { k: 'line', x1: 3, y1: -1.5, x2: 2.2, y2: -1.5 },
      { k: 'line', x1: 3, y1: 1.5, x2: 2.2, y2: 1.5 },
      { k: 'text', x: 0, y: 0.3, s: 'E', size: 1, anchor: 'c' },
    ],
    keywords: ['amp', 'gain', 'e'],
  },
  {
    id: 'vccs',
    name: 'VCCS (G)',
    category: 'source',
    description: 'Voltage-controlled current source, transconductance Gm = Iout / (Vp − Vn).',
    refPrefix: 'G',
    spicePrefix: 'G',
    pins: [
      { name: 'OUT+', direction: 'output', electrical: 'analog', x: 3, y: -1.5 },
      { name: 'OUT-', direction: 'output', electrical: 'analog', x: 3, y: 1.5 },
      { name: 'IN+', direction: 'input', electrical: 'analog', x: -3, y: -1.5 },
      { name: 'IN-', direction: 'input', electrical: 'analog', x: -3, y: 1.5 },
    ],
    params: [
      { name: 'gm', kind: 'number', unit: 'siemens', default: 1e-3, description: 'Transconductance', sensitive: true },
      { name: 'rout', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Output resistance (0 = ideal)' },
      { name: 'rin', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Input resistance (0 = ideal, no loading)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: {
      ...sourceCard('VCCS', []),
      claims: [
        { phenomenon: 'transconductance', level: Accuracy.REALISTIC, detail: 'Stamped exactly: i_out = gm·(v+ − v−).' },
        { phenomenon: 'nonlinearity / bandwidth', level: Accuracy.NOT_MODELED, detail: 'Perfectly linear transconductance.' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['G'] },
    symbol: [
      { k: 'poly', pts: [-2.2, -1.8, 2.2, -1.8, 2.2, 1.8, -2.2, 1.8], t: 0.16 },
      { k: 'line', x1: -3, y1: -1.5, x2: -2.2, y2: -1.5 },
      { k: 'line', x1: -3, y1: 1.5, x2: -2.2, y2: 1.5 },
      { k: 'line', x1: 3, y1: -1.5, x2: 2.2, y2: -1.5 },
      { k: 'line', x1: 3, y1: 1.5, x2: 2.2, y2: 1.5 },
      { k: 'text', x: 0, y: 0.3, s: 'G', size: 1, anchor: 'c' },
    ],
    keywords: ['transconductance', 'g'],
  },
  {
    id: 'cccs',
    name: 'CCCS (F)',
    category: 'source',
    description: 'Current-controlled current source with ratio β.',
    refPrefix: 'F',
    spicePrefix: 'F',
    pins: [
      { name: 'OUT+', direction: 'output', electrical: 'analog', x: 3, y: -1.5 },
      { name: 'OUT-', direction: 'output', electrical: 'analog', x: 3, y: 1.5 },
      { name: 'CTRL+', direction: 'input', electrical: 'analog', x: -3, y: -1.5 },
      { name: 'CTRL-', direction: 'input', electrical: 'analog', x: -3, y: 1.5 },
    ],
    params: [
      { name: 'gain', kind: 'number', unit: '', default: 1, description: 'Current gain β', sensitive: true },
      { name: 'rout', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Output resistance (0 = ideal)' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: {
      ...sourceCard('CCCS', []),
      claims: [
        { phenomenon: 'current transfer', level: Accuracy.REALISTIC, detail: 'Controlled by the current through the control branch, which is a solver unknown — so the coupling is exact.' },
        { phenomenon: 'bandwidth', level: Accuracy.NOT_MODELED, detail: 'Flat response.' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['F'] },
    symbol: [
      { k: 'poly', pts: [-2.2, -1.8, 2.2, -1.8, 2.2, 1.8, -2.2, 1.8], t: 0.16 },
      { k: 'line', x1: -3, y1: -1.5, x2: -2.2, y2: -1.5 },
      { k: 'line', x1: -3, y1: 1.5, x2: -2.2, y2: 1.5 },
      { k: 'line', x1: 3, y1: -1.5, x2: 2.2, y2: -1.5 },
      { k: 'line', x1: 3, y1: 1.5, x2: 2.2, y2: 1.5 },
      { k: 'text', x: 0, y: 0.3, s: 'F', size: 1, anchor: 'c' },
    ],
    keywords: ['mirror', 'current gain'],
  },
  {
    id: 'ccvs',
    name: 'CCVS (H)',
    category: 'source',
    description: 'Current-controlled voltage source with transresistance Rm.',
    refPrefix: 'H',
    spicePrefix: 'H',
    pins: [
      { name: 'OUT+', direction: 'output', electrical: 'analog', x: 3, y: -1.5 },
      { name: 'OUT-', direction: 'output', electrical: 'analog', x: 3, y: 1.5 },
      { name: 'CTRL+', direction: 'input', electrical: 'analog', x: -3, y: -1.5 },
      { name: 'CTRL-', direction: 'input', electrical: 'analog', x: -3, y: 1.5 },
    ],
    params: [
      { name: 'gain', kind: 'number', unit: 'ohm', default: 1000, description: 'Transresistance (V/A)', sensitive: true },
      { name: 'rout', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Output resistance' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: {
      ...sourceCard('CCVS', []),
      claims: [
        { phenomenon: 'transresistance', level: Accuracy.REALISTIC, detail: 'v_out = Rm · i_ctrl, imposed exactly.' },
        { phenomenon: 'bandwidth', level: Accuracy.NOT_MODELED, detail: 'Flat response.' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['H'] },
    symbol: [
      { k: 'poly', pts: [-2.2, -1.8, 2.2, -1.8, 2.2, 1.8, -2.2, 1.8], t: 0.16 },
      { k: 'line', x1: -3, y1: -1.5, x2: -2.2, y2: -1.5 },
      { k: 'line', x1: -3, y1: 1.5, x2: -2.2, y2: 1.5 },
      { k: 'line', x1: 3, y1: -1.5, x2: 2.2, y2: -1.5 },
      { k: 'line', x1: 3, y1: 1.5, x2: 2.2, y2: 1.5 },
      { k: 'text', x: 0, y: 0.3, s: 'H', size: 1, anchor: 'c' },
    ],
    keywords: ['transresistance', 'h'],
  },
];

// ---------------------------------------------------------------------------
// POWER / INFRASTRUCTURE
// ---------------------------------------------------------------------------

export const POWER_SPECS: ComponentSpec[] = [
  {
    id: 'ground',
    name: 'Ground',
    category: 'power',
    description: 'Reference node (0 V). Every circuit needs at least one.',
    refPrefix: 'GND',
    spicePrefix: '',
    pins: [{ name: '0', direction: 'passive', electrical: 'ground', x: 0, y: -1 }],
    params: [],
    accuracy: Accuracy.REALISTIC,
    model: {
      family: 'Reference node',
      version: '1.0.0',
      claims: [{ phenomenon: 'reference', level: Accuracy.REALISTIC, detail: 'Node 0 of the MNA system. Exact by definition.' }],
      equations: ['V(node) = 0'],
      parameters: [],
      limitations: ['An ideal ground has zero impedance at all frequencies; real grounds do not. Model the impedance explicitly with R/L if it matters.'],
      references: [],
      levels: [0, 1, 2, 3],
    },
    support: { logic: true, electrical: true, thermal: false, lowersTo: [] },
    symbol: [
      { k: 'line', x1: 0, y1: -1, x2: 0, y2: 0 },
      { k: 'line', x1: -0.8, y1: 0, x2: 0.8, y2: 0, t: 0.16 },
      { k: 'line', x1: -0.5, y1: 0.35, x2: 0.5, y2: 0.35, t: 0.16 },
      { k: 'line', x1: -0.2, y1: 0.7, x2: 0.2, y2: 0.7, t: 0.16 },
    ],
    keywords: ['gnd', '0', 'earth', 'reference'],
  },
  {
    id: 'battery',
    name: 'Battery',
    category: 'power',
    description: 'Real battery: open-circuit voltage, internal resistance, capacity, temperature dependence, state of charge.',
    refPrefix: 'BT',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'supply', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'ground', x: 0, y: 2 },
    ],
    params: [
      { name: 'vnom', kind: 'number', unit: 'volt', default: 3.7, description: 'Nominal (open circuit, full) voltage', sensitive: true },
      { name: 'rseries', kind: 'number', unit: 'ohm', default: 0.1, min: 0.0001, description: 'Internal series resistance', sensitive: true },
      { name: 'capacity', kind: 'number', unit: '', default: 2.5, min: 1e-9, description: 'Capacity in ampere-hours' },
      { name: 'soc', kind: 'number', unit: '', default: 1, min: 0, max: 1, description: 'Initial state of charge' },
      { name: 'cutoff', kind: 'number', unit: 'volt', default: 3.0, description: 'Voltage at 0% SoC (linear interpolation of the discharge curve)' },
      { name: 'tempco', kind: 'number', unit: '', default: -2e-3, description: 'Voltage temperature coefficient (1/°C)' },
      { name: 'rth', kind: 'number', unit: '', default: 10, min: 0.01, description: 'Thermal resistance (°C/W)' },
      { name: 'cth', kind: 'number', unit: '', default: 400, min: 1e-6, description: 'Thermal capacitance (J/°C)' },
    ],
    accuracy: Accuracy.APPROXIMATED,
    model: {
      family: 'Battery: Thévenin + linear SoC discharge curve',
      version: '1.0.0',
      claims: [
        { phenomenon: 'terminal voltage under load', level: Accuracy.REALISTIC, detail: 'V = Voc(SoC) − I·Rint, with charge counted by integrating the current. This is the standard Thévenin battery model and matches load-step measurements well.' },
        { phenomenon: 'discharge curve', level: Accuracy.APPROXIMATED, detail: 'Linear interpolation between vnom (full) and cutoff (empty). Real Li-ion cells have a flat plateau then a knee; use a 2-RC model for more accuracy (not implemented).' },
        { phenomenon: 'temperature effect', level: Accuracy.APPROXIMATED, detail: 'Linear voltage coefficient and temperature-dependent internal resistance (Arrhenius-like factor).' },
        { phenomenon: 'ageing / cycle life / thermal runaway', level: Accuracy.NOT_MODELED, detail: 'Not modelled.' },
      ],
      equations: ['V = Voc(SoC,w)·(1 + tempco·ΔT) − I·Rint(T)', 'dSoC/dt = −I/(3600·capacity)'],
      parameters: [
        { name: 'vnom', unit: 'V', meaning: 'nominal cell voltage' },
        { name: 'rseries', unit: 'Ω', meaning: 'Thévenin resistance' },
        { name: 'capacity', unit: 'Ah', meaning: 'charge capacity' },
      ],
      limitations: ['No diffusion dynamics, no hysteresis, no ageing.', 'The discharge curve is linear, which underestimates the plateau-to-knee shape.'],
      references: ['Thévenin equivalent battery models, Plett (2015)'],
      levels: [1, 2, 3],
    },
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['VDC'] },
    symbol: [
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1 },
      { k: 'line', x1: 0, y1: 1, x2: 0, y2: 2 },
      { k: 'line', x1: -1, y1: -1, x2: 1, y2: -1, t: 0.2 },
      { k: 'line', x1: -0.55, y1: -0.6, x2: 0.55, y2: -0.6, t: 0.2 },
      { k: 'line', x1: -1, y1: -0.2, x2: 1, y2: -0.2, t: 0.2 },
      { k: 'line', x1: -0.55, y1: 0.2, x2: 0.55, y2: 0.2, t: 0.2 },
      { k: 'line', x1: -1, y1: 0.6, x2: 1, y2: 0.6, t: 0.2 },
      { k: 'line', x1: -0.55, y1: 1, x2: 0.55, y2: 1, t: 0.2 },
    ],
    keywords: ['batt', 'cell', 'accumulator'],
  },
  {
    id: 'heatsink',
    name: 'Heatsink',
    category: 'power',
    description: 'Thermal mass with a thermal resistance to ambient; attach devices to it for electro-thermal simulation.',
    refPrefix: 'HS',
    spicePrefix: '*',
    pins: [{ name: 'T', direction: 'passive', electrical: 'any', x: 0, y: -1, description: 'Thermal attachment (connect to device exposed thermal node or via thermal pad)' }],
    params: [
      { name: 'rth', kind: 'number', unit: '', default: 5, min: 0.01, description: 'Thermal resistance to ambient (°C/W)', sensitive: true },
      { name: 'cth', kind: 'number', unit: '', default: 20, min: 1e-6, description: 'Thermal capacitance (J/°C)', sensitive: true },
      { name: 'forced', kind: 'number', unit: '', default: 0, min: 0, description: 'Forced-air multiplier on the thermal resistance (1 = none, 0.3 = strong airflow)' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: {
      family: 'Lumped thermal node',
      version: '1.0.0',
      claims: [
        { phenomenon: 'heat conduction to ambient', level: Accuracy.REALISTIC, detail: 'dT/dt = (P_in − (T − Tamb)/Rth)/Cth integrated by the same implicit integrator as the electrical problem.' },
        { phenomenon: 'convection nonlinearity', level: Accuracy.APPROXIMATED, detail: 'A constant Rth is used; real convection is nonlinear (h ∝ ΔT^0.25) and Rth therefore varies with the temperature rise.' },
        { phenomenon: 'thermal capacitance of the fin mass / radiation', level: Accuracy.NOT_MODELED, detail: 'Radiation is folded into Rth implicitly at the reference condition.' },
      ],
      equations: ['Cth·dT/dt = P_in − (T − Tamb)/Rth'],
      parameters: [
        { name: 'rth', unit: '°C/W', meaning: 'thermal resistance to ambient' },
        { name: 'cth', unit: 'J/°C', meaning: 'thermal mass' },
      ],
      limitations: ['Single-node (no temperature gradient across the sink).', 'Constant Rth.'],
      references: ['Fischer Elektronik heatsink datasheets'],
      levels: [3],
    },
    support: { logic: false, electrical: false, thermal: true, lowersTo: [] },
    symbol: [
      { k: 'line', x1: 0, y1: -1, x2: 0, y2: -0.3 },
      { k: 'rect', x: -1.4, y: -0.3, w: 2.8, h: 0.5, t: 0.15 },
      { k: 'line', x1: -1, y1: 0.2, x2: -1, y2: 1.1, t: 0.15 },
      { k: 'line', x1: -0.5, y1: 0.2, x2: -0.5, y2: 1.1, t: 0.15 },
      { k: 'line', x1: 0, y1: 0.2, x2: 0, y2: 1.1, t: 0.15 },
      { k: 'line', x1: 0.5, y1: 0.2, x2: 0.5, y2: 1.1, t: 0.15 },
      { k: 'line', x1: 1, y1: 0.2, x2: 1, y2: 1.1, t: 0.15 },
    ],
    keywords: ['thermal', 'cooling', 'sink'],
  },
  {
    id: 'thermal_pad',
    name: 'Thermal Pad',
    category: 'power',
    description: 'Thermal resistance between two thermal nodes (die to case, case to heatsink, insulating pad).',
    refPrefix: 'TP',
    spicePrefix: '*',
    pins: [
      { name: 'A', direction: 'passive', electrical: 'any', x: 0, y: -1.5 },
      { name: 'B', direction: 'passive', electrical: 'any', x: 0, y: 1.5 },
    ],
    params: [
      { name: 'rth', kind: 'number', unit: '', default: 1.5, min: 0.0001, description: 'Thermal resistance between the two nodes (°C/W)', sensitive: true },
      { name: 'cth', kind: 'number', unit: '', default: 0.5, min: 0, description: 'Thermal capacitance (°C/W)' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: {
      family: 'Thermal resistor',
      version: '1.0.0',
      claims: [{ phenomenon: 'heat flow', level: Accuracy.REALISTIC, detail: 'Q = ΔT/Rth, exact for the lumped element.' }],
      equations: ['Q = (Ta − Tb)/Rth'],
      parameters: [{ name: 'rth', unit: '°C/W', meaning: 'thermal resistance' }],
      limitations: ['No interface material thickness/area calculation — enter the datasheet value directly.'],
      references: ['Bergquist thermal interface datasheets'],
      levels: [3],
    },
    support: { logic: false, electrical: false, thermal: true, lowersTo: [] },
    symbol: [
      { k: 'line', x1: 0, y1: -1.5, x2: 0, y2: -0.6 },
      { k: 'line', x1: 0, y1: 0.6, x2: 0, y2: 1.5 },
      { k: 'rect', x: -0.8, y: -0.6, w: 1.6, h: 1.2, t: 0.14 },
      { k: 'text', x: 0, y: 0.35, s: 'R', size: 0.8, anchor: 'c' },
    ],
    keywords: ['thermal', 'interface', 'pad'],
  },
];

// ---------------------------------------------------------------------------
// INSTRUMENTS
// ---------------------------------------------------------------------------

const instrumentCard = (what: string, detail: string): ModelCard => ({
  family: 'Virtual instrument',
  version: '1.0.0',
  claims: [
    { phenomenon: 'measurement', level: Accuracy.REALISTIC, detail },
    { phenomenon: 'loading effect', level: Accuracy.APPROXIMATED, detail: 'Input impedance is parameterised (default: voltmeter ∞Ω, ammeter 0Ω). Set real values to see the loading error a real instrument would introduce.' },
    { phenomenon: 'instrument bandwidth / noise / ADC', level: Accuracy.NOT_MODELED, detail: 'Measurements are read from the exact solver state: no ADC quantisation, no probe noise, no bandwidth limit. This is a *measurement* instrument, not a simulation of a bench instrument.' },
  ],
  equations: [],
  parameters: [],
  limitations: ['Displays exact solver values; real instruments add noise, bandwidth limits and loading.'],
  references: [],
  levels: [0, 1, 2, 3],
});

export const INSTRUMENT_SPECS: ComponentSpec[] = [
  {
    id: 'voltmeter',
    name: 'Voltmeter',
    category: 'instrument',
    description: 'Measures differential voltage (DC, AC, RMS, min, max) with a configurable input resistance.',
    refPrefix: 'VM',
    spicePrefix: 'R',
    pins: [
      { name: '+', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'rin', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Input resistance (0 = ideal — no loading)' },
      { name: 'label', kind: 'string', default: '', description: 'Display label' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: instrumentCard('Voltmeter', 'V = V(+) − V(−) taken from the converged node solution at every accepted time step.'),
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['PROBE'] },
    symbol: [
      { k: 'circle', cx: 0, cy: 0, r: 1.1, t: 0.15 },
      { k: 'text', x: 0, y: 0.4, s: 'V', size: 1.1, anchor: 'c' },
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1.1 },
      { k: 'line', x1: 0, y1: 1.1, x2: 0, y2: 2 },
    ],
    keywords: ['vm', 'dmm', 'measure'],
  },
  {
    id: 'ammeter',
    name: 'Ammeter',
    category: 'instrument',
    description: 'Measures branch current with a configurable shunt resistance.',
    refPrefix: 'AM',
    spicePrefix: 'V',
    pins: [
      { name: '+', direction: 'passive', electrical: 'analog', x: 0, y: -2 },
      { name: '-', direction: 'passive', electrical: 'analog', x: 0, y: 2 },
    ],
    params: [
      { name: 'rshunt', kind: 'number', unit: 'ohm', default: 0, min: 0, description: 'Shunt resistance (0 = ideal ammeter, no burden voltage)' },
      { name: 'label', kind: 'string', default: '', description: 'Display label' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: instrumentCard('Ammeter', 'I = current through the branch (a solver unknown when rshunt = 0, else computed from the shunt drop).'),
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['AMMETER'] },
    symbol: [
      { k: 'circle', cx: 0, cy: 0, r: 1.1, t: 0.15 },
      { k: 'text', x: 0, y: 0.4, s: 'A', size: 1.1, anchor: 'c' },
      { k: 'line', x1: 0, y1: -2, x2: 0, y2: -1.1 },
      { k: 'line', x1: 0, y1: 1.1, x2: 0, y2: 2 },
    ],
    keywords: ['am', 'current', 'dmm'],
  },
  {
    id: 'wattmeter',
    name: 'Wattmeter',
    category: 'instrument',
    description: 'Four-terminal power meter: measures instantaneous V·I, plus real/reactive/apparent power for periodic signals.',
    refPrefix: 'WM',
    spicePrefix: 'X',
    pins: [
      { name: 'V+', direction: 'passive', electrical: 'analog', x: -2, y: -1.5 },
      { name: 'V-', direction: 'passive', electrical: 'analog', x: -2, y: 1.5 },
      { name: 'I+', direction: 'passive', electrical: 'analog', x: 2, y: -1.5 },
      { name: 'I-', direction: 'passive', electrical: 'analog', x: 2, y: 1.5 },
    ],
    params: [
      { name: 'rshunt', kind: 'number', unit: 'ohm', default: 0.01, min: 1e-9, description: 'Current-sense shunt resistance' },
      { name: 'periods', kind: 'number', unit: '', default: 4, min: 0.1, description: 'Number of periods used for the real/reactive power average' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: {
      ...instrumentCard('Wattmeter', 'P(t) = v(t)·i(t) sampled every accepted step; real power is the time average over whole periods.'),
      claims: [
        { phenomenon: 'instantaneous power', level: Accuracy.REALISTIC, detail: 'Exact product of the measured voltage and current.' },
        { phenomenon: 'real / reactive / apparent power', level: Accuracy.APPROXIMATED, detail: 'Computed from averages over an integer number of detected periods; if the signal is not periodic the value is labelled as an estimate with the observation window in the report.' },
      ],
    },
    support: { logic: false, electrical: true, thermal: false, lowersTo: ['WATTMETER'] },
    symbol: [
      { k: 'rect', x: -1.8, y: -1.8, w: 3.6, h: 3.6, t: 0.16, r: 0.2 },
      { k: 'text', x: 0, y: 0.3, s: 'W', size: 1.2, anchor: 'c' },
      { k: 'line', x1: -2, y1: -1.5, x2: -1.8, y2: -1.5 },
      { k: 'line', x1: -2, y1: 1.5, x2: -1.8, y2: 1.5 },
      { k: 'line', x1: 2, y1: -1.5, x2: 1.8, y2: -1.5 },
      { k: 'line', x1: 2, y1: 1.5, x2: 1.8, y2: 1.5 },
    ],
    keywords: ['power', 'watt', 'energy'],
  },
  {
    id: 'probe',
    name: 'Probe',
    category: 'instrument',
    description: 'Generic measurement probe: voltage, current, power, temperature, logic state, frequency.',
    refPrefix: 'PR',
    spicePrefix: '',
    pins: [{ name: 'P', direction: 'passive', electrical: 'any', x: 0, y: -1 }],
    params: [
      { name: 'kind', kind: 'choice', default: 'voltage', choices: ['voltage', 'current', 'power', 'temperature', 'logic', 'frequency'], description: 'What to measure at this net', sensitive: true },
      { name: 'label', kind: 'string', default: '', description: 'Label shown on the schematic' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: instrumentCard('Probe', 'Reads the requested quantity from the simulation state for the net it is attached to.'),
    support: { logic: true, electrical: true, thermal: true, lowersTo: ['PROBE'] },
    symbol: [
      { k: 'line', x1: 0, y1: -1, x2: 0, y2: -0.2 },
      { k: 'circle', cx: 0, cy: 0.3, r: 0.5, t: 0.15 },
      { k: 'line', x1: -0.35, y1: -0.05, x2: 0.35, y2: 0.65, t: 0.12 },
    ],
    keywords: ['scope', 'measure', 'testpoint', 'logic'],
  },
  {
    id: 'thermometer',
    name: 'Thermometer',
    category: 'instrument',
    description: 'Temperature sensor on a net/thermal node (NTC-based or ideal readout).',
    refPrefix: 'TH',
    spicePrefix: 'R',
    pins: [
      { name: 'T', direction: 'passive', electrical: 'any', x: 0, y: -1.5 },
      { name: 'OUT', direction: 'output', electrical: 'analog', x: 2, y: 0, optional: true, description: 'Optional analogue output (e.g. 10 mV/°C)' },
    ],
    params: [
      { name: 'ideal', kind: 'boolean', default: true, description: 'True = direct readout of the thermal node; false = simulate an NTC divider output' },
      { name: 'sens', kind: 'number', unit: 'volt', default: 0.01, description: 'Output sensitivity per °C (NTC mode)' },
    ],
    accuracy: Accuracy.REALISTIC,
    model: instrumentCard('Thermometer', 'Reads the temperature of the attached thermal node directly from the thermal network solution.'),
    support: { logic: false, electrical: true, thermal: true, lowersTo: ['THERMO'] },
    symbol: [
      { k: 'rect', x: -0.9, y: -1.3, w: 1.8, h: 2.2, t: 0.15, r: 0.25 },
      { k: 'line', x1: 0, y1: -1.5, x2: 0, y2: -1.3 },
      { k: 'line', x1: 0, y1: 0.9, x2: 0, y2: 1.3 },
      { k: 'circle', cx: 0, cy: 1.5, r: 0.25 },
      { k: 'text', x: 0, y: 0.2, s: 'T', size: 0.9, anchor: 'c' },
    ],
    keywords: ['temp', 'thermal', 'sensor'],
  },
  {
    id: 'logic_probe',
    name: 'Logic Probe',
    category: 'instrument',
    description: 'Displays the logic state (0/1/X/Z) of a net with an LED indicator.',
    refPrefix: 'LP',
    spicePrefix: '',
    pins: [{ name: 'IN', direction: 'input', electrical: 'digital', x: 0, y: -1.5 }],
    params: [{ name: 'threshold', kind: 'number', unit: 'volt', default: 1.65, description: 'Logic threshold voltage used in electrical simulations' }],
    accuracy: Accuracy.REALISTIC,
    model: instrumentCard('Logic probe', 'Logic state derived from the net voltage relative to the threshold (electrical simulation) or read directly from the logic engine.'),
    support: { logic: true, electrical: true, thermal: false, lowersTo: ['PROBE'] },
    symbol: [
      { k: 'line', x1: 0, y1: -1.5, x2: 0, y2: -0.7 },
      { k: 'circle', cx: 0, cy: 0, r: 0.6, t: 0.15 },
      { k: 'circle', cx: 0, cy: 0, r: 0.3, fill: true },
    ],
    keywords: ['logic', 'state', 'led'],
  },
];

/** All non-digital, non-semiconductor specs. */
export const BASE_SPECS: ComponentSpec[] = [
  ...PASSIVE_SPECS,
  ...SWITCHING_SPECS,
  ...SOURCE_SPECS,
  ...POWER_SPECS,
  ...INSTRUMENT_SPECS,
];

export { REF };
